## Regression Exercise

In [2]:
import numpy as np

pollution_data = np.genfromtxt('data/pollution_cleaneddata.csv', delimiter=',', skip_header=1)

pollution_data

array([[3.600000e+01, 2.700000e+01, 7.100000e+01, 8.100000e+00,
        3.340000e+00, 1.140000e+01, 8.150000e+01, 3.243000e+03,
        8.800000e+00, 4.260000e+01, 1.170000e+01, 2.100000e+01,
        1.500000e+01, 5.900000e+01, 5.900000e+01, 9.218700e+02],
       [3.500000e+01, 2.300000e+01, 7.200000e+01, 1.110000e+01,
        3.140000e+00, 1.100000e+01, 7.880000e+01, 4.281000e+03,
        3.500000e+00, 5.070000e+01, 1.440000e+01, 8.000000e+00,
        1.000000e+01, 3.900000e+01, 5.700000e+01, 9.978750e+02],
       [4.400000e+01, 2.900000e+01, 7.400000e+01, 1.040000e+01,
        3.210000e+00, 9.800000e+00, 8.160000e+01, 4.260000e+03,
        8.000000e-01, 3.940000e+01, 1.240000e+01, 6.000000e+00,
        6.000000e+00, 3.300000e+01, 5.400000e+01, 9.623540e+02],
       [4.700000e+01, 4.500000e+01, 7.900000e+01, 6.500000e+00,
        3.410000e+00, 1.110000e+01, 7.750000e+01, 3.125000e+03,
        2.710000e+01, 5.020000e+01, 2.060000e+01, 1.800000e+01,
        8.000000e+00, 2.400000e+01, 5

In [3]:
x = pollution_data[:, 10] # POOR
y = pollution_data[:, 15] # MORT
y

array([ 921.87 ,  997.875,  962.354,  982.291, 1071.289, 1030.38 ,
        934.7  ,  899.529, 1001.902,  912.347, 1017.613, 1024.885,
        970.467,  985.95 ,  958.839,  860.101,  936.234,  871.766,
        959.221,  941.181,  891.708,  871.338,  971.122,  887.466,
        952.529,  968.665,  919.729,  844.053,  861.833,  989.265,
       1006.49 ,  861.439,  929.15 ,  857.622,  961.009,  923.234,
       1113.156,  994.648, 1015.023,  991.29 ,  893.991,  938.5  ,
        946.185, 1025.502,  874.281,  953.56 ,  839.709,  911.701,
        790.733,  899.264,  904.155,  950.672,  972.464,  912.202,
        967.803,  823.764, 1003.502,  895.696,  911.817,  954.442])

In [5]:
def loess(y, x, k, x_0):
    pred = np.zeros(len(x_0))
    sd = np.zeros(len(x_0))

    for i, x0 in enumerate(x_0):

        d = np.abs(x - x0) # distance
        idx = np.argsort(d)[:k] # nearest k
        d_k, x_k, y_k = d[idx], x[idx], y[idx] # nearest point coordinates

        h = d_k.max()
        u = d_k / h if h > 0 else np.zeros(k)

        w = np.clip(1 - u, 0, None) # weighting 1 for centre and 0 for edge

        sum_w = np.sum(w)
        x_bar = np.sum(w * x_k) / sum_w # weighted mean x
        y_bar = np.sum(w * y_k) / sum_w # weighted mean y

        nom = np.sum(w * (x_k - x_bar) * (y_k - y_bar)) # nominator
        denom = np.sum(w * ((x_k - x_bar)** 2)) # denominator
        beta_1 = nom / denom

        beta_0 = y_bar - beta_1 * x_bar

        pred[i] = beta_0 + beta_1 * x0

    return pred, sd


x_0 = np.array([10, 18, 25])
pred, sd = loess(y, x, 10, x_0)
pred

array([ 893.28088224,  957.59668824, 1016.91718426])